### ISSUE TITLE
Enconding option: RGB or HEX

### ISSUE THREAD

**Issue by vyscond** [SahAssar/bolt-bootstrap-colorpicker#1]
I think it's useful if we could set which encode is desired. Better than that is to create function on the field to convert on the fly but i don't know if it's possible.

btw, thanks for the awesome extension.

**Comment by SahAssar** [comment]
PR's are welecome! I hoped to get this done, but it's been a year and I should stop pretending... So either PR it (which I'd be very grateful for) or I'll get this done when we need it at the company :)

**Comment by vyscond** [comment]
Oh gosh! 😂  Fair enough
